#!/bin/sh

docker run -t \
  -v "$(pwd):/blah" \
  -v "$(pwd)/.docker-stack:/root/.stack/snapshots" \
  crogers/stack-ide-atom-docker:stack-0.1.3.1_nightly-2015-08-06 \
  /bin/sh -c "cd blah && ./gulp $@"
