flags: {}
packages:
- haskell
- stack-ide/ide-backend/ide-backend-common
- stack-ide/stack-ide-api
extra-deps:
- HUnit-1.3.0.0
- QuickCheck-2.8.1
- StateVar-1.1.0.1
- ansi-terminal-0.6.2.3
- auto-update-0.1.2.2
- base-orphans-0.4.4
- base64-bytestring-1.0.0.1
- bifunctors-5
- blaze-builder-0.4.0.1
- bytestring-builder-0.10.6.0.0
- bytestring-trie-0.2.4.1
- cereal-0.4.1.1
- comonad-4.2.7.2
- conduit-1.2.5
- conduit-extra-1.1.9.1
- contravariant-1.3.3
- crypto-api-0.13.2
- data-accessor-0.2.2.6
- distributive-0.4.4
- entropy-0.3.7
- exceptions-0.8.0.2
- fast-logger-2.4.1
- fingertree-0.1.1.0
- free-4.12.1
- haskell-lexer-1.0
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-discover-2.2.0
- hspec-expectations-0.7.2
- lifted-base-0.2.3.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- monad-logger-0.3.14
- monad-loops-0.4.3
- nats-1
- network-2.6.2.1
- prelude-extras-0.4.0.2
- pretty-show-1.6.8.2
- profunctors-5.1.1
- pureMD5-2.1.2.1
- quickcheck-io-0.1.2
- random-1.1
- resourcet-1.1.6
- semigroupoids-5.0.0.4
- semigroups-0.17.0.1
- setenv-0.1.1.3
- stm-chans-3.0.0.4
- streaming-commons-0.1.14.2
- tagged-0.8.1
- temporary-1.2.0.3
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- void-0.7.1
- zlib-0.6.1.1
compiler-check: match-exact
resolver: ghcjs-0.1.0.20150924_ghc-7.10.2
